import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'bn';

type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// English translations
const enTranslations: Record<string, string> = {
  // Navbar
  'nav.home': 'Home',
  'nav.bookNow': 'Book Now',
  'nav.medicine': 'Medicine & Diagnosis',
  'nav.blog': 'Blog',
  'nav.about': 'About',
  'nav.contact': 'Contact',
  'nav.login': 'Login',
  'nav.register': 'Register',
  'nav.cart': 'Cart',
  'language': 'EN',
  
  // Footer
  'footer.quickLinks': 'Quick Links',
  'footer.services': 'Services',
  'footer.onlineConsultations': 'Online Consultations',
  'footer.prescriptionManagement': 'Prescription Management',
  'footer.medicineRecommendations': 'Medicine Recommendations',
  'footer.followUpCare': 'Follow-up Care',
  'footer.description': 'Your trusted online clinic providing professional medical consultations and prescription services with experienced doctors.',
  'footer.phone': '+1 (555) 123-4567',
  'footer.email': 'contact@medicmate.com',
  'footer.address': '123 Medical Center, Health City, HC 12345',
  'footer.copyright': '© 2024 MedicMate. All rights reserved. | Privacy Policy | Terms of Service',
  
  // Home Page
  'home.badge': 'Trusted Medical Care',
  'home.title1': 'Your Trusted',
  'home.title2': 'Online Clinic',
  'home.description': 'Professional medical consultations and prescription services from the comfort of your home. Expert care when you need it most.',
  'home.bookAppointment': 'Book Appointment',
  'home.learnMore': 'Learn More',
  'home.doctorTitle': 'Dr. Sarah Smith',
  'home.doctorSpecialty': 'Internal Medicine Specialist',
  'home.doctorRating': '(4.9/5 from 200+ patients)',
  'home.doctorDescription': 'With over 15 years of experience in internal medicine, Dr. Smith provides comprehensive healthcare services with a focus on preventive care and patient education.',
  'home.boardCertified': 'Board Certified',
  'home.experience': '15+ Years Experience',
  'home.licensed': 'Licensed in 3 States',
  'home.viewProfile': 'View Full Profile',
  'home.whyChoose': 'Why Choose MedicMate?',
  'home.whyChooseDescription': 'We provide comprehensive healthcare services designed around your convenience and well-being.',
  'home.feature1Title': 'Easy Booking',
  'home.feature1Description': 'Schedule appointments online in just a few clicks. Choose your preferred time slot.',
  'home.feature2Title': 'Prescription Management',
  'home.feature2Description': 'Digital prescriptions sent directly to your pharmacy. Track your medication history.',
  'home.feature3Title': 'Medicine Recommendations',
  'home.feature3Description': 'Get personalized medicine recommendations based on your symptoms and medical history.',
  'home.testimonials': 'What Our Patients Say',
  'home.testimonialsSubtitle': 'Real experiences from our valued patients',
  'home.ctaTitle': 'Ready to Get Started?',
  'home.ctaDescription': 'Book your consultation today and experience quality healthcare from home.',
  'home.scheduleAppointment': 'Schedule Your Appointment',
  
  // Medicine Page
  'medicine.title': 'Medicine & Diagnosis',
  'medicine.description': 'Browse our comprehensive medicine database, request prescriptions, and book diagnostic tests',
  'medicine.tabMedicines': 'Medicines',
  'medicine.tabDiagnostic': 'Diagnostic Tests',
  'medicine.searchFilterMedicines': 'Search & Filter Medicines',
  'medicine.searchPlaceholder': 'Search medicines by name or usage...',
  'medicine.filterByCondition': 'Filter by condition',
  'medicine.availability': 'Availability',
  'medicine.showing': 'Showing',
  'medicine.of': 'of',
  'medicine.medicines': 'medicines',
  'medicine.addToCart': 'Add to Cart',
  'medicine.requestPrescription': 'Request Prescription',
  'medicine.askDoctor': 'Ask Doctor',
  'medicine.diagnostic.askDoctor': 'Ask Doctor',
  'medicine.searchFilterDiagnostic': 'Search & Filter Diagnostic Tests',
  'medicine.searchDiagnosticPlaceholder': 'Search diagnostic tests...',
  'medicine.filterByCategory': 'Filter by category',
  'medicine.diagnosticTests': 'Diagnostic Tests',
  'medicine.price': 'Price',
  'medicine.resultsTime': 'Results Time',
  'medicine.bookNow': 'Book Now',
  'medicine.needHelp': 'Need Help Choosing the Right Test?',
  'medicine.helpDescription': 'Our healthcare professionals can help you determine which diagnostic tests are appropriate for your symptoms and health concerns.',
  'medicine.consultDoctor': 'Consult a Doctor',
  'medicine.teleconsult.title': 'Need a Prescription?',
  'medicine.teleconsult.description': 'Consult with Dr. Sarah Smith for personalized medicine recommendations and digital prescriptions.',
  'medicine.teleconsult.button': 'Schedule a Consultation',
  'medicine.diagnostic.new': 'New',
  'medicine.category.allCategories': 'All Categories',
  'medicine.category.bloodTests': 'Blood Tests',
  'medicine.category.imaging': 'Imaging',
  'medicine.category.cardiovascular': 'Cardiovascular',
  'medicine.category.neurological': 'Neurological',
  'medicine.category.gastrointestinal': 'Gastrointestinal',

  // Blog Page
  'blog.hero.title': 'MedicMate Health Blog',
  'blog.hero.description': 'Expert insights, health tips, and medical information to help you live your healthiest life',
  'blog.hero.subscribeButton': 'Subscribe to Updates',
  'blog.hero.browseCategoriesButton': 'Browse Categories',
  'blog.featuredArticles.title': 'Featured Articles',
  'blog.featuredArticles.viewAllButton': 'View All Articles',
  'blog.latestHealthInsights.title': 'Latest Health Insights',
  'blog.healthTips.title': 'Health Tips & Advice',
  'blog.healthTips.description': 'Maintaining good health requires a holistic approach that includes proper nutrition, regular exercise, adequate sleep, and stress management. Here at MedicMate, we believe in empowering our patients with knowledge to make informed health decisions.',
  'blog.healthTips.quickTipsTitle': 'Quick Health Tips:',
  'blog.healthTips.tip1': 'Stay hydrated by drinking at least 8 glasses of water daily',
  'blog.healthTips.tip2': 'Aim for 7-9 hours of quality sleep each night',
  'blog.healthTips.tip3': 'Include a variety of colorful fruits and vegetables in your diet',
  'blog.healthTips.tip4': 'Take short breaks during work to reduce eye strain and mental fatigue',
  'blog.healthTips.tip5': 'Practice mindfulness or meditation to manage stress',
  'blog.healthTips.conclusion': 'Remember that small, consistent changes often lead to the most sustainable health improvements. Consult with our healthcare professionals for personalized advice tailored to your specific needs.',
  'blog.cta.title': 'Have a Health Question?',
  'blog.cta.description': 'Our team of qualified healthcare professionals is ready to help you with personalized advice.',
    'blog.cta.bookConsultationButton': 'Book a Consultation',
    'blog.cta.contactUsButton': 'Contact Us',

    'blog.featuredPosts.post1.title': 'Understanding Telemedicine: The Future of Healthcare',
    'blog.featuredPosts.post1.excerpt': 'Explore how telemedicine is revolutionizing patient care and making healthcare more accessible than ever before.',
    'blog.featuredPosts.post1.category': 'Telemedicine',
    'blog.featuredPosts.post1.author': 'Dr. Sarah Johnson',
    'blog.featuredPosts.post1.date': 'June 15, 2024',
    'blog.featuredPosts.post1.readTime': '8 min read',
    'blog.featuredPosts.post1.tag1': 'telemedicine',
    'blog.featuredPosts.post1.tag2': 'digital health',
    'blog.featuredPosts.post1.tag3': 'healthcare access',

    'blog.featuredPosts.post2.title': 'Preventive Health Measures Everyone Should Know',
    'blog.featuredPosts.post2.excerpt': 'Learn about essential preventive health measures that can help you maintain optimal health and prevent common diseases.',
    'blog.featuredPosts.post2.category': 'Preventive Care',
    'blog.featuredPosts.post2.author': 'Dr. Michael Chen',
    'blog.featuredPosts.post2.date': 'June 10, 2024',
    'blog.featuredPosts.post2.readTime': '6 min read',
    'blog.featuredPosts.post2.tag1': 'preventive care',
    'blog.featuredPosts.post2.tag2': 'health tips',
    'blog.featuredPosts.post2.tag3': 'wellness',

    'blog.featuredPosts.post3.title': 'Mental Health in the Digital Age',
    'blog.featuredPosts.post3.excerpt': 'Discover strategies for maintaining good mental health while navigating the challenges of our increasingly digital world.',
    'blog.featuredPosts.post3.category': 'Mental Health',
    'blog.featuredPosts.post3.author': 'Dr. Emily Rodriguez',
    'blog.featuredPosts.post3.date': 'June 5, 2024',
    'blog.featuredPosts.post3.readTime': '7 min read',
    'blog.featuredPosts.post3.tag1': 'mental health',
    'blog.featuredPosts.post3.tag2': 'digital wellbeing',
    'blog.featuredPosts.post3.tag3': 'stress management',

    'blog.recentArticles.title': 'Recent Articles',
    'blog.recentPosts.post1.title': 'The Role of Nutrition in Immune System Health',
    'blog.recentPosts.post1.category': 'Nutrition',
    'blog.recentPosts.post1.date': 'June 1, 2024',
    'blog.recentPosts.post1.readTime': '5 min read',

    'blog.recentPosts.post2.title': 'Understanding Common Medications and Their Side Effects',
    'blog.recentPosts.post2.category': 'Medications',
    'blog.recentPosts.post2.date': 'May 28, 2024',
    'blog.recentPosts.post2.readTime': '6 min read',

    'blog.recentPosts.post3.title': 'Sleep Hygiene: Tips for Better Rest',
    'blog.recentPosts.post3.category': 'Wellness',
    'blog.recentPosts.post3.date': 'May 25, 2024',
    'blog.recentPosts.post3.readTime': '4 min read',

    'blog.recentPosts.post4.title': 'Chronic Disease Management: A Comprehensive Guide',
    'blog.recentPosts.post4.category': 'Chronic Care',
    'blog.recentPosts.post4.date': 'May 20, 2024',
    'blog.recentPosts.post4.readTime': '9 min read',

    'blog.categories.telemedicine': 'Telemedicine',
    'blog.categories.preventiveCare': 'Preventive Care',
    'blog.categories.mentalHealth': 'Mental Health',
    'blog.categories.nutrition': 'Nutrition',
    'blog.categories.medications': 'Medications',
    'blog.categories.wellness': 'Wellness',
    'blog.categories.chronicCare': 'Chronic Care',

    'blog.sidebar.categoriesTitle': 'Categories',
    'blog.sidebar.newsletterTitle': 'Subscribe to Our Newsletter',
    'blog.sidebar.newsletterDescription': 'Get the latest health tips and medical updates delivered directly to your inbox.',
    'blog.sidebar.newsletterPlaceholder': 'Your email address',
    'blog.sidebar.newsletterButton': 'Subscribe',
  'blog.sidebar.tagsTitle': 'Popular Tags',

  // Contact Page
  'contact.hero.title': 'Get in Touch',
  'contact.hero.description': "Have questions about our services? Need help with your appointment? We're here to help you every step of the way.",
  'contact.form.fullNameLabel': 'Full Name',
  'contact.form.fullNamePlaceholder': 'Enter your full name',
  'contact.form.emailLabel': 'Email Address',
  'contact.form.emailPlaceholder': 'Enter your email',
  'contact.form.subjectLabel': 'Subject',
  'contact.form.subjectPlaceholder': 'What is this regarding?',
  'contact.form.messageLabel': 'Message',
  'contact.form.messagePlaceholder': 'How can we help you?',
  'contact.form.sendButton': 'Send Message',
  'contact.info.title': 'Contact Information',
  'contact.info.phoneLabel': 'Phone',
  'contact.info.phoneNumber': '+1 (555) 123-4567',
  'contact.info.emailLabel': 'Email',

  // Login Page
  'login.subtitle': 'Sign in to your account',
  'login.welcomeBack': 'Welcome Back',
  'login.patientTab': 'Patient',
  'login.doctorTab': 'Doctor',
  'login.patient.emailLabel': 'Email Address',
  'login.patient.emailPlaceholder': 'Enter your email',
  'login.patient.passwordLabel': 'Password',
  'login.patient.passwordPlaceholder': 'Enter your password',
  'login.patient.forgotPassword': 'Forgot password?',
  'login.patient.signInButton': 'Sign In as Patient',
  'login.patient.noAccountText': "Don't have an account?",
  'login.patient.signUpLink': 'Sign up here',
  'login.doctor.emailLabel': 'Doctor Email',
  'login.doctor.emailPlaceholder': 'Enter doctor email',
  'login.doctor.passwordLabel': 'Password',
  'login.doctor.passwordPlaceholder': 'Enter password',
  'login.doctor.securePortalNotice': 'This is a secure admin portal for medical professionals only.',
  'login.doctor.signInButton': 'Sign In as Doctor',
  'login.securityNotice': 'Your information is protected with enterprise-grade encryption and complies with HIPAA privacy standards.',
  'login.toast.missingInfoTitle': 'Missing Information',
  'login.toast.missingInfoDescription': 'Please fill in all fields.',
  'login.toast.patientLoginSuccessTitle': 'Login Successful!',
  'login.toast.patientLoginSuccessDescription': 'Welcome back! Redirecting to your dashboard.',
  'login.toast.doctorLoginSuccessTitle': 'Doctor Login Successful!',
  'login.toast.doctorLoginSuccessDescription': 'Welcome back, Dr. Smith!',

  // Register Page
  'register.subtitle': 'Join MedicMate Care Today',
  'register.welcome': 'Register as a Patient or Doctor',
  'register.patientTab': 'Patient',
  'register.doctorTab': 'Doctor',

  'register.patient.fullNameLabel': 'Full Name *',
  'register.patient.fullNamePlaceholder': 'Enter your full name',
  'register.patient.emailLabel': 'Email *',
  'register.patient.emailPlaceholder': 'Enter your email',
  'register.patient.phoneLabel': 'Phone Number *',
  'register.patient.phonePlaceholder': 'Enter your phone number',
  'register.patient.dobLabel': 'Date of Birth *',
  'register.patient.dobPlaceholder': 'Select your date of birth',
  'register.patient.passwordLabel': 'Password *',
  'register.patient.passwordPlaceholder': 'Create a strong password',
  'register.patient.confirmPasswordLabel': 'Confirm Password *',
  'register.patient.confirmPasswordPlaceholder': 'Confirm your password',
  'register.patient.agreeToTerms': 'I agree to the',
  'register.patient.termsOfService': 'Terms of Service',
  'register.patient.and': 'and',
  'register.patient.privacyPolicy': 'Privacy Policy',
  'register.patient.createAccountButton': 'Create Account',
  'register.patient.alreadyAccount': 'Already have an account?',
  'register.patient.signInHere': 'Sign in here',

  'register.doctor.securePortalNotice': 'Doctor registration requires verification of medical credentials.',
  'register.doctor.fullNameLabel': 'Full Name *',
  'register.doctor.fullNamePlaceholder': 'Enter your full name',
  'register.doctor.emailLabel': 'Professional Email *',
  'register.doctor.emailPlaceholder': 'Enter your professional email',
  'register.doctor.passwordLabel': 'Password *',
  'register.doctor.passwordPlaceholder': 'Create a strong password',
  'register.doctor.confirmPasswordLabel': 'Confirm Password *',
  'register.doctor.confirmPasswordPlaceholder': 'Confirm your password',
  'register.doctor.agreeToTerms': 'I agree to the',
  'register.doctor.termsOfService': 'Terms of Service',
  'register.doctor.and': 'and',
  'register.doctor.privacyPolicy': 'Privacy Policy',
  'register.doctor.submitApplicationButton': 'Submit Doctor Application',
  'register.doctor.alreadyAccount': 'Already have an account?',
  'register.doctor.signInHere': 'Sign in here',
  'contact.info.emailAddress': 'contact@medicmate.com',
  'contact.info.addressLabel': 'Address',
  'contact.info.address': '123 Health St, Medical City, MC 12345',
  'contact.info.hoursLabel': 'Working Hours',
  'contact.info.hoursMonFri': 'Mon - Fri: 9:00 AM - 5:00 PM',
  'contact.info.hoursSat': 'Sat: 10:00 AM - 2:00 PM',
  'contact.info.hoursSun': 'Sun: Closed',
  'contact.faq.title': 'Frequently Asked Questions',
  'contact.faq.q1': 'How do I book an appointment?',
  'contact.faq.a1': "You can book an appointment through our online booking system by clicking 'Book Appointment' on our homepage. Select your preferred date and time, fill in your information, and you'll receive a confirmation email.",
  'contact.faq.q2': 'What types of consultations do you offer?',
  'contact.faq.a2': 'We offer general consultations, follow-up appointments, prescription renewals, symptom assessments, second opinions, and chronic disease management. All consultations are conducted via secure video calls or phone calls.',
  'contact.faq.q3': 'How much does a consultation cost?',
  'contact.faq.a3': 'Our standard consultation fee is $75 for a 30-minute session. Follow-up appointments are $50. We accept most major insurance plans and offer payment plans for uninsured patients.',
  'contact.faq.q4': 'Can you prescribe medications online?',
  'contact.faq.a4': 'Yes, Dr. Smith can prescribe most medications during your consultation. Prescriptions are sent digitally to your preferred pharmacy. Some controlled substances may require additional verification.',
  'contact.faq.q5': 'What states are you licensed to practice in?',
  'contact.faq.a5': "Dr. Smith is currently licensed to practice medicine in New York, California, and Florida. We're working on expanding to additional states to serve more patients.",
  'contact.faq.q6': 'How secure is my medical information?',
  'contact.faq.a6': 'We use enterprise-grade encryption and comply with all HIPAA privacy standards. Your medical information is stored securely and never shared without your explicit consent.',
  'contact.faq.q7': 'What if I need emergency medical care?',
  'contact.faq.a7': 'For medical emergencies, please call 911 or go to your nearest emergency room. Our telemedicine services are for non-emergency consultations and routine medical care.',
  'contact.faq.q8': 'Can I get lab test results through your platform?',
  'contact.faq.a8': 'Yes, Dr. Smith can review and discuss lab results during your consultation. You can upload your test results through our secure patient portal or email them before your appointment.',
  'contact.toast.missingInfoTitle': 'Missing Information',
  'contact.toast.missingInfoDescription': 'Please fill in all required fields.',
  'contact.toast.messageSentTitle': 'Message Sent!',
  'contact.toast.messageSentDescription': "Thank you for contacting us. We'll get back to you within 24 hours.",
  
    // About Page
  'about.hero.badge': 'About MedicMate',
  'about.hero.title': 'Revolutionizing Healthcare',
  'about.hero.subtitle': 'One Patient at a Time',
  'about.hero.description': 'MedicMate was born from a simple belief: everyone deserves access to quality, personalized healthcare. Through innovative technology and compassionate care, we\'re making that vision a reality.',
  'about.story.title': 'Our Story',
  'about.story.paragraph1': 'Dr. Sarah Smith founded MedicMate in 2019 with a clear mission: to bridge the gap between patients and quality healthcare through technology. Having witnessed the challenges patients face in accessing timely medical care, she envisioned a platform that would make healthcare more accessible, affordable, and personal.',
  'about.story.paragraph2': 'What started as a small telemedicine practice has grown into a comprehensive healthcare platform serving over 1,200 patients across multiple states. Our commitment to excellence and patient-first approach has earned us a 98% satisfaction rate and numerous accolades in the digital health space.',
  'about.story.button': 'Learn More About Dr. Smith',
  'about.timeline.title': 'Our Journey',
  'about.timeline.description': 'Key milestones in our mission to transform healthcare',
  'about.timeline.year1': '2019',
  'about.timeline.title1': 'MedicMate Founded',
  'about.timeline.description1': 'Dr. Sarah Smith founded MedicMate with a vision to make quality healthcare accessible to everyone through technology.',
  'about.timeline.year2': '2020',
  'about.timeline.title2': 'Telemedicine Pioneer',
  'about.timeline.description2': 'Became one of the first practices to offer comprehensive telemedicine services during the pandemic.',
  'about.timeline.year3': '2022',
  'about.timeline.title3': '1000+ Patients Served',
  'about.timeline.description3': 'Reached the milestone of serving over 1000 patients with a 98% satisfaction rate.',
  'about.timeline.year4': '2024',
  'about.timeline.title4': 'Advanced Platform Launch',
  'about.timeline.description4': 'Launched our advanced online platform with AI-assisted diagnostics and enhanced patient experience.',
  'about.achievements.title': 'Our Impact',
  'about.achievements.description': 'Numbers that reflect our commitment to excellence',
  'about.achievements.patientsNumber': '1,200+',
  'about.achievements.patientsLabel': 'Happy Patients',
  'about.achievements.satisfactionRateNumber': '98%',
  'about.achievements.satisfactionRateLabel': 'Satisfaction Rate',
  'about.achievements.responseTimeNumber': '< 2 hours',
  'about.achievements.responseTimeLabel': 'Average Response Time',
  'about.achievements.experienceNumber': '15+',
  'about.achievements.experienceLabel': 'Years Experience',

  'about.vision.title': 'Our Vision',
  'about.vision.description': 'To become the leading digital healthcare platform that makes quality medical care accessible to everyone, regardless of location or circumstances. We envision a world where technology eliminates barriers to healthcare and empowers patients to take control of their health journey.',
  'about.mission.title': 'Our Mission',
  'about.mission.description': 'To provide personalized, compassionate, and evidence-based healthcare through innovative technology. We are committed to building lasting relationships with our patients, ensuring they receive the highest quality care while maintaining the convenience and comfort of home.',

  'about.cta.title': 'Ready to Experience Better Healthcare?',
  'about.cta.description': 'Join thousands of satisfied patients who have discovered the convenience and quality of MedicMate\'s personalized healthcare services.',
  'about.cta.bookAppointmentButton': 'Book Your Appointment',
  'about.cta.contactUsButton': 'Contact Us',

  // Book Appointment Page
  'bookAppointment.toast.missingInfoTitle': 'Missing Information',
  'bookAppointment.toast.missingInfoDescription': 'Please fill in all required fields.',
  'bookAppointment.toast.bookedTitle': 'Appointment Booked!',
  'bookAppointment.toast.bookedDescription': 'Your appointment has been successfully scheduled. You will receive a confirmation email shortly.',
  'bookAppointment.title': 'Book Your Appointment',
  'bookAppointment.subtitle': 'Schedule a consultation with Dr. Sarah Smith at your convenience',
  'bookAppointment.cardTitle': 'Appointment Details',
  'bookAppointment.personalInfoTitle': 'Personal Information',
  'bookAppointment.fullNameLabel': 'Full Name',
  'bookAppointment.fullNamePlaceholder': 'Enter your full name',
  'bookAppointment.emailLabel': 'Email Address',
  'bookAppointment.emailPlaceholder': 'Enter your email address',
  'bookAppointment.phoneLabel': 'Phone Number',
  'bookAppointment.phonePlaceholder': 'Enter your phone number',
  'bookAppointment.serviceTypeLabel': 'Service Type',
  'bookAppointment.selectServicePlaceholder': 'Select a service',
  'bookAppointment.service.generalConsultation': 'General Consultation',
  'bookAppointment.service.followUpAppointment': 'Follow-up Appointment',
  'bookAppointment.service.prescriptionRenewal': 'Prescription Renewal',
  'bookAppointment.service.symptomAssessment': 'Symptom Assessment',
  'bookAppointment.service.secondOpinion': 'Second Opinion',
  'bookAppointment.service.chronicDiseaseManagement': 'Chronic Disease Management',
  'bookAppointment.dateTimeTitle': 'Date & Time',
  'bookAppointment.selectDateLabel': 'Select Date',
  'bookAppointment.pickDatePlaceholder': 'Pick a date',
  'bookAppointment.availableTimeSlotsLabel': 'Available Time Slots',
  'bookAppointment.timeSlot.nineAM': '9:00 AM',
  'bookAppointment.timeSlot.nineThirtyAM': '9:30 AM',
  'bookAppointment.timeSlot.tenAM': '10:00 AM',
  'bookAppointment.timeSlot.tenThirtyAM': '10:30 AM',
  'bookAppointment.timeSlot.elevenAM': '11:00 AM',
  'bookAppointment.timeSlot.elevenThirtyAM': '11:30 AM',
  'bookAppointment.timeSlot.twoPM': '2:00 PM',
  'bookAppointment.timeSlot.twoThirtyPM': '2:30 PM',
  'bookAppointment.timeSlot.threePM': '3:00 PM',
  'bookAppointment.timeSlot.threeThirtyPM': '3:30 PM',
  'bookAppointment.timeSlot.fourPM': '4:00 PM',
  'bookAppointment.timeSlot.fourThirtyPM': '4:30 PM',
  'bookAppointment.timeSlot.fivePM': '5:00 PM',
  'bookAppointment.notesPlaceholder': 'Any additional notes or requests?',
  'bookAppointment.confirmButton': 'Confirm Appointment',

  // Medicine Page - Medicine Details
  'medicine.ibuprofen.usage': 'Pain Relief & Anti-inflammatory',
  'medicine.ibuprofen.description': 'Effective relief for headaches, muscle pain, and inflammation.',
  'medicine.amoxicillin.usage': 'Antibiotic',
  'medicine.amoxicillin.description': 'Broad-spectrum antibiotic for bacterial infections.',
  'medicine.lisinopril.usage': 'Blood Pressure Control',
  'medicine.lisinopril.description': 'ACE inhibitor for managing high blood pressure.',
  'medicine.metformin.usage': 'Diabetes Management',
  'medicine.metformin.description': 'First-line treatment for type 2 diabetes.',
  'medicine.albuterol.usage': 'Asthma Inhaler',
  'medicine.albuterol.description': 'Fast-acting bronchodilator for asthma relief.',
  'medicine.omeprazole.usage': 'Acid Reflux Relief',
  'medicine.omeprazole.description': 'Proton pump inhibitor for gastric acid reduction.',

  'medicine.ibuprofen.price': '$12.99',
  'medicine.amoxicillin.price': '$18.50',
  'medicine.lisinopril.price': '$15.25',
  'medicine.metformin.price': '$22.00',
  'medicine.albuterol.price': '$35.75',
  'medicine.omeprazole.price': '$14.50',

  // Medicine Page - Conditions
  'medicine.condition.allConditions': 'All Conditions',
  'medicine.condition.painManagement': 'Pain Management',
  'medicine.condition.infections': 'Infections',
  'medicine.condition.cardiovascular': 'Cardiovascular',
  'medicine.condition.diabetes': 'Diabetes',
  'medicine.condition.respiratory': 'Respiratory',
  'medicine.condition.digestive': 'Digestive',

  // Medicine Page - Availability
  'medicine.availability.all': 'All',
  'medicine.availability.inStock': 'In Stock',
  'medicine.availability.prescriptionRequired': 'Prescription Required',

  // Medicine Page - Diagnostic Tests
  'medicine.diagnostic.bloodTest.name': 'Complete Blood Count (CBC)',
  'medicine.diagnostic.bloodTest.category': 'Blood Test',
  'medicine.diagnostic.bloodTest.description': 'Measures different components of blood, useful for detecting infections, anemia, and other disorders.',
  'medicine.diagnostic.urineTest.name': 'Urinalysis',
  'medicine.diagnostic.urineTest.category': 'Urine Test',
  'medicine.diagnostic.urineTest.description': 'Checks for various diseases and conditions by examining the content of urine.',
  'medicine.diagnostic.xray.name': 'Chest X-Ray',
  'medicine.diagnostic.xray.category': 'Imaging',
  'medicine.diagnostic.xray.description': 'Provides images of the heart, lungs, blood vessels, and bones of the chest and spine.',
  'medicine.diagnostic.mri.name': 'MRI Scan (Brain)',
  'medicine.diagnostic.mri.category': 'Imaging',
  'medicine.diagnostic.mri.description': 'Detailed images of the brain and surrounding tissues, used to diagnose various neurological conditions.',
  'medicine.diagnostic.ecg.name': 'Electrocardiogram (ECG)',
  'medicine.diagnostic.ecg.category': 'Cardiac Test',
  'medicine.diagnostic.ecg.description': 'Records the electrical signals of the heart to detect heart conditions.',
  'medicine.diagnostic.ultrasound.name': 'Abdominal Ultrasound',
  'medicine.diagnostic.ultrasound.category': 'Imaging',
  'medicine.diagnostic.ultrasound.description': 'Uses sound waves to create images of organs and structures inside the abdomen.',
  'medicine.diagnostic.ultrasound.price': '$75.00',
  'medicine.diagnostic.popular': 'Popular',
  'medicine.diagnostic.common': 'Common',
  'medicine.diagnostic.specialized': 'Specialized',
  'medicine.diagnostic.fastingRequired': 'Fasting Required',
  'medicine.diagnostic.doctorReferral': 'Doctor Referral',
  'medicine.diagnostic.preparationRequired': 'Preparation Required',
  'medicine.diagnostic.time.12hours': '12 Hours',
  'medicine.diagnostic.time.1-2days': '1-2 Days',
  'medicine.diagnostic.time.2-3days': '2-3 Days',
  'medicine.diagnostic.time.1-2weeks': '1-2 Weeks',
  'medicine.diagnostic.xray': 'Chest X-Ray',
  'medicine.diagnostic.xray.type': 'Imaging',
  'medicine.diagnostic.xray.details': 'Produces images of the chest, including the heart, lungs, blood vessels, and bones to diagnose conditions.',
  'medicine.diagnostic.xray.price': '$120.00',
  'medicine.diagnostic.lipidPanel.name': 'Lipid Panel',
  'medicine.diagnostic.lipidPanel.category': 'Cardiovascular Health',
  'medicine.diagnostic.lipidPanel.description': 'Measures cholesterol levels to assess risk of cardiovascular disease. Includes total cholesterol, HDL, LDL, and triglycerides.',
  'medicine.diagnostic.lipidPanel.price': '$65.00',
  'medicine.diagnostic.brainMri.name': 'Brain MRI',
  'medicine.diagnostic.brainMri.category': 'Advanced Imaging',
  'medicine.diagnostic.brainMri.description': 'Creates detailed images of the brain and brain stem using magnetic fields and radio waves. Helps diagnose tumors, strokes, and other conditions.',
  'medicine.diagnostic.brainMri.price': '$850.00',
  'medicine.diagnostic.colonoscopy.name': 'Colonoscopy',
  'medicine.diagnostic.colonoscopy.category': 'Gastrointestinal Procedure',
  'medicine.diagnostic.colonoscopy.description': 'Examines the lining of the colon to detect abnormalities such as polyps, ulcers, and cancer. Includes sedation and recovery time.',
  'medicine.diagnostic.colonoscopy.price': '$1,200.00',
  'medicine.diagnostic.helpChoosingTest.title': 'Need Help Choosing the Right Test?',
  'medicine.diagnostic.helpChoosingTest.description': 'Our healthcare professionals can help you determine which diagnostic tests are appropriate for your symptoms and health concerns.',
  'medicine.diagnostic.consultDoctor': 'Consult with a Doctor',
  
  // New medicine translations
  'medicine.acetaminophen.usage': 'Pain reliever and fever reducer',
  'medicine.acetaminophen.description': 'Safe and effective for treating mild to moderate pain and reducing fever.',
  'medicine.aspirin.usage': 'Pain relief and blood thinner',
  'medicine.aspirin.description': 'Reduces pain, inflammation, and risk of heart attack when used as prescribed.',

  // Cart
  'cart.title': 'Your Cart',
  'cart.empty.title': 'Your cart is empty',
  'cart.empty.description': 'Add some medicines or diagnostic tests to get started.',
  'cart.continueShopping': 'Continue Shopping',
  'cart.clearAll': 'Clear All',
  'cart.orderSummary': 'Order Summary',
  'cart.subtotal': 'Subtotal',
  'cart.shipping': 'Shipping',
  'cart.free': 'Free',
  'cart.total': 'Total',
  'cart.checkout': 'Proceed to Checkout',
  'cart.medicine': 'Medicine',
  'cart.diagnostic': 'Diagnostic Test',
  'cart.itemAdded': 'Item Added',
  'cart.addedToCart': 'has been added to your cart',

  // Diagnostic Test Categories
  'medicine.diagnostic.category.allCategories': 'All Categories',
  'medicine.diagnostic.category.bloodTest': 'Blood Test',
  'medicine.diagnostic.category.urineTest': 'Urine Test',
  'medicine.diagnostic.category.imaging': 'Imaging',
  'medicine.diagnostic.category.cardiacTest': 'Cardiac Test',

  // Diagnostic Test Price and Time
  'medicine.diagnostic.price': 'Price',
  'medicine.diagnostic.resultsTime': 'Results Time',
  'medicine.diagnostic.time.24hours': '24 Hours',
  'medicine.diagnostic.time.48hours': '48 Hours',
  'medicine.diagnostic.time.72hours': '72 Hours',
  'medicine.diagnostic.time.3days': '3 Days',
  'medicine.diagnostic.time.5days': '5 Days',
  'medicine.diagnostic.time.1week': '1 Week',

  // Emergency Contact
  'contact.emergency.title': 'Emergency Contact',
  'contact.emergency.subtitle': 'For Medical Emergencies',
  'contact.emergency.description': 'Please call 911 or go to your nearest emergency room. Our telemedicine services are for non-emergency consultations only.'

};

// Bangla translations
const bnTranslations: Record<string, string> = {
  // Navbar
  'nav.home': 'হোম',
  'nav.bookNow': 'অ্যাপয়েন্টমেন্ট বুক করুন',
  'nav.medicine': 'ঔষধ ও ডায়াগনসিস',
  'medicine.diagnostic.new': 'নতুন',
  'nav.blog': 'ব্লগ',
  'nav.about': 'আমাদের সম্পর্কে',
  'nav.contact': 'যোগাযোগ',
  'nav.login': 'লগইন',
  'nav.register': 'রেজিস্টার',
  'language': 'BN',
  
  // Footer
  'footer.quickLinks': 'দ্রুত লিঙ্ক',
  'footer.services': 'সেবাসমূহ',
  'footer.onlineConsultations': 'অনলাইন পরামর্শ',
  'footer.prescriptionManagement': 'প্রেসক্রিপশন ব্যবস্থাপনা',
  'footer.medicineRecommendations': 'ঔষধ সুপারিশ',
  'footer.followUpCare': 'ফলো-আপ কেয়ার',
  'footer.description': 'আপনার বাড়ির আরাম থেকে পেশাদার মেডিকেল পরামর্শ এবং প্রেসক্রিপশন সেবা। যখন আপনার সবচেয়ে বেশি প্রয়োজন তখন বিশেষজ্ঞ যত্ন।',
  'footer.phone': '+1 (555) 123-4567',
  'footer.email': 'contact@medicmate.com',
  'footer.address': '123 মেডিকেল সেন্টার, হেলথ সিটি, এইচসি 12345',
  'footer.copyright': '© ২০২৪ মেডিকমেট। সর্বস্বত্ব সংরক্ষিত। | গোপনীয়তা নীতি | সেবার শর্তাবলী',
  
  // Home Page
  'home.badge': 'বিশ্বস্ত মেডিকেল কেয়ার',
  'home.title1': 'আপনার বিশ্বস্ত',
  'home.title2': 'অনলাইন ক্লিনিক',
  'home.description': 'আপনার বাড়ির আরাম থেকে পেশাদার মেডিকেল পরামর্শ এবং প্রেসক্রিপশন সেবা। যখন আপনার সবচেয়ে বেশি প্রয়োজন তখন বিশেষজ্ঞ যত্ন।',
  'home.bookAppointment': 'অ্যাপয়েন্টমেন্ট বুক করুন',
  'home.learnMore': 'আরও জানুন',
  'home.doctorTitle': 'ডাঃ সারা স্মিথ',
  'home.doctorSpecialty': 'অভ্যন্তরীণ মেডিসিন বিশেষজ্ঞ',
  'home.doctorRating': '(২০০+ রোগীর মধ্যে ৪.৯/৫)',
  'home.doctorDescription': 'অভ্যন্তরীণ মেডিসিনে ১৫ বছরেরও বেশি অভিজ্ঞতার সাথে, ডাঃ স্মিথ প্রতিরোধমূলক যত্ন এবং রোগীর শিক্ষার উপর ফোকাস সহ ব্যাপক স্বাস্থ্যসেবা প্রদান করেন।',
  'home.boardCertified': 'বোর্ড সার্টিফাইড',
  'home.experience': '১৫+ বছরের অভিজ্ঞতা',
  'home.licensed': '৩টি রাজ্যে লাইসেন্সপ্রাপ্ত',
  'home.viewProfile': 'সম্পূর্ণ প্রোফাইল দেখুন',
  'home.whyChoose': 'কেন মেডিকমেট বেছে নেবেন?',
  'home.whyChooseDescription': 'আমরা আপনার সুবিধা এবং সুস্থতার চারপাশে ডিজাইন করা ব্যাপক স্বাস্থ্যসেবা প্রদান করি।',
  'home.feature1Title': 'সহজ বুকিং',
  'home.feature1Description': 'কয়েকটি ক্লিকেই অনলাইনে অ্যাপয়েন্টমেন্ট শিডিউল করুন। আপনার পছন্দের সময় স্লট বেছে নিন।',
  'home.feature2Title': 'প্রেসক্রিপশন ব্যবস্থাপনা',
  'home.feature2Description': 'ডিজিটাল প্রেসক্রিপশন সরাসরি আপনার ফার্মেসিতে পাঠানো হয়। আপনার ওষুধের ইতিহাস ট্র্যাক করুন।',
  'home.feature3Title': 'ঔষধ সুপারিশ',
  'home.feature3Description': 'আপনার উপসর্গ এবং মেডিকেল ইতিহাসের উপর ভিত্তি করে ব্যক্তিগতকৃত ঔষধের সুপারিশ পান।',
  'home.testimonials': 'আমাদের রোগীরা কী বলেন',
  'home.testimonialsSubtitle': 'আমাদের মূল্যবান রোগীদের বাস্তব অভিজ্ঞতা',
  'home.ctaTitle': 'শুরু করতে প্রস্তুত?',
  'home.ctaDescription': 'আজই আপনার পরামর্শ বুক করুন এবং বাড়ি থেকে মানসম্পন্ন স্বাস্থ্যসেবা অনুভব করুন।',
  'home.scheduleAppointment': 'আপনার অ্যাপয়েন্টমেন্ট শিডিউল করুন',
  
  // Medicine Page
  'medicine.title': 'ঔষধ ও ডায়াগনসিস',
  'medicine.description': 'আমাদের ব্যাপক ঔষধ ডাটাবেস ব্রাউজ করুন, প্রেসক্রিপশন অনুরোধ করুন, এবং ডায়াগনস্টিক পরীক্ষা বুক করুন',
  'medicine.tabMedicines': 'ঔষধ',
  'medicine.tabDiagnostic': 'ডায়াগনস্টিক পরীক্ষা',
  'medicine.searchFilterMedicines': 'ঔষধ অনুসন্ধান ও ফিল্টার করুন',
  'medicine.searchPlaceholder': 'নাম বা ব্যবহার দ্বারা ঔষধ অনুসন্ধান করুন...',
  'medicine.filterByCondition': 'অবস্থা দ্বারা ফিল্টার করুন',
  'medicine.availability': 'উপলব্ধতা',
  'medicine.showing': 'দেখাচ্ছে',
  'medicine.of': 'এর মধ্যে',
  'medicine.medicines': 'ঔষধ',
  'medicine.addToCart': 'কার্টে যোগ করুন',
  'medicine.requestPrescription': 'প্রেসক্রিপশন অনুরোধ করুন',
  'medicine.askDoctor': 'ডাক্তারকে জিজ্ঞাসা করুন',
  'medicine.searchFilterDiagnostic': 'ডায়াগনস্টিক পরীক্ষা অনুসন্ধান ও ফিল্টার করুন',
  'medicine.searchDiagnosticPlaceholder': 'ডায়াগনস্টিক পরীক্ষা অনুসন্ধান করুন...',
  'medicine.filterByCategory': 'বিভাগ দ্বারা ফিল্টার করুন',
  'medicine.diagnosticTests': 'ডায়াগনস্টিক পরীক্ষা',
  'medicine.price': 'মূল্য',
  'medicine.resultsTime': 'ফলাফলের সময়',
  'medicine.bookNow': 'এখনই বুক করুন',
  'medicine.needHelp': 'সঠিক পরীক্ষা বেছে নিতে সাহায্য প্রয়োজন?',
  'medicine.helpDescription': 'Our healthcare professionals can help you determine which diagnostic tests are appropriate for your symptoms and health concerns.',
  'medicine.consultDoctor': 'Consult with a Doctor',

  // Contact Page
  'contact.hero.title': 'যোগাযোগ করুন',
  'contact.hero.description': 'আমাদের পরিষেবা সম্পর্কে প্রশ্ন আছে? আপনার অ্যাপয়েন্টমেন্টের জন্য সাহায্য প্রয়োজন? আমরা আপনাকে প্রতিটি পদক্ষেপে সাহায্য করতে এখানে আছি।',
  'contact.form.fullNameLabel': 'পুরো নাম',
  'contact.form.fullNamePlaceholder': 'আপনার পুরো নাম লিখুন',
  'contact.form.emailLabel': 'ইমেল ঠিকানা',
  'contact.form.emailPlaceholder': 'আপনার ইমেল লিখুন',
  'contact.form.subjectLabel': 'বিষয়',
  'contact.form.subjectPlaceholder': 'এটি কি বিষয়ে?',
  'contact.form.messageLabel': 'বার্তা',
  'contact.form.messagePlaceholder': 'আমরা আপনাকে কিভাবে সাহায্য করতে পারি?',
  'contact.form.sendButton': 'বার্তা পাঠান',
  'contact.info.title': 'যোগাযোগের তথ্য',
  'contact.info.phoneLabel': 'ফোন',
  'contact.info.phoneNumber': '+1 (555) 123-4567',
  'contact.info.emailLabel': 'ইমেল',
  'contact.info.emailAddress': 'contact@medicmate.com',
  'contact.info.addressLabel': 'ঠিকানা',
  'contact.info.address': '123 হেলথ স্ট্রিট, মেডিকেল সিটি, এমসি 12345',
  'contact.info.hoursLabel': 'কাজের সময়',
  'contact.info.hoursMonFri': 'সোম - শুক্র: সকাল ৯:০০ - বিকাল ৫:০০',
  'contact.info.hoursSat': 'শনি: সকাল ১০:০০ - বিকাল ২:০০',
  'contact.info.hoursSun': 'রবি: বন্ধ',
  'contact.faq.title': 'সাধারণ জিজ্ঞাসা',
  'contact.faq.q1': 'আমি কিভাবে একটি অ্যাপয়েন্টমেন্ট বুক করব?',
  'contact.faq.a1': 'আপনি আমাদের হোমপেজে \'অ্যাপয়েন্টমেন্ট বুক করুন\' ক্লিক করে আমাদের অনলাইন বুকিং সিস্টেমের মাধ্যমে একটি অ্যাপয়েন্টমেন্ট বুক করতে পারেন। আপনার পছন্দের তারিখ এবং সময় নির্বাচন করুন, আপনার তথ্য পূরণ করুন এবং আপনি একটি নিশ্চিতকরণ ইমেল পাবেন।',
  'contact.faq.q2': 'আপনি কি ধরনের পরামর্শ দেন?',
  'contact.faq.a2': 'আমরা সাধারণ পরামর্শ, ফলো-আপ অ্যাপয়েন্টমেন্ট, প্রেসক্রিপশন নবায়ন, উপসর্গ মূল্যায়ন, দ্বিতীয় মতামত এবং দীর্ঘস্থায়ী রোগ ব্যবস্থাপনা অফার করি। সমস্ত পরামর্শ সুরক্ষিত ভিডিও কল বা ফোন কলের মাধ্যমে পরিচালিত হয়।',
  'contact.faq.q3': 'একটি পরামর্শের খরচ কত?',
  'contact.faq.a3': 'আমাদের স্ট্যান্ডার্ড পরামর্শ ফি ৩০ মিনিটের সেশনের জন্য $৭৫। ফলো-আপ অ্যাপয়েন্টমেন্ট $৫০। আমরা বেশিরভাগ প্রধান বীমা পরিকল্পনা গ্রহণ করি এবং বীমাহীন রোগীদের জন্য পেমেন্ট প্ল্যান অফার করি।',
  'contact.faq.q4': 'আপনি কি অনলাইনে ঔষধ প্রেসক্রাইব করতে পারেন?',
  'contact.faq.a4': 'হ্যাঁ, ডাঃ স্মিথ আপনার পরামর্শের সময় বেশিরভাগ ঔষধ প্রেসক্রাইব করতে পারেন। প্রেসক্রিপশনগুলি আপনার পছন্দের ফার্মেসিতে ডিজিটালভাবে পাঠানো হয়। কিছু নিয়ন্ত্রিত পদার্থের জন্য অতিরিক্ত যাচাইকরণের প্রয়োজন হতে পারে।',
  'contact.faq.q5': 'আপনি কোন রাজ্যগুলিতে অনুশীলন করার জন্য লাইসেন্সপ্রাপ্ত?',
  'contact.faq.a5': 'ডাঃ স্মিথ বর্তমানে নিউ ইয়র্ক, ক্যালিফোর্নিয়া এবং ফ্লোরিডায় চিকিৎসা অনুশীলন করার জন্য লাইসেন্সপ্রাপ্ত। আমরা আরও রোগীদের সেবা দেওয়ার জন্য অতিরিক্ত রাজ্যগুলিতে প্রসারিত করার জন্য কাজ করছি।',
  'contact.faq.q6': 'আমার মেডিকেল তথ্য কতটা সুরক্ষিত?',
  'contact.faq.a6': 'আমরা এন্টারপ্রাইজ-গ্রেড এনক্রিপশন ব্যবহার করি এবং সমস্ত HIPAA গোপনীয়তা মান মেনে চলি। আপনার মেডিকেল তথ্য সুরক্ষিতভাবে সংরক্ষণ করা হয় এবং আপনার স্পষ্ট সম্মতি ছাড়া কখনও শেয়ার করা হয় না।',
  'contact.faq.q7': 'আমার যদি জরুরি চিকিৎসার প্রয়োজন হয় তাহলে কি হবে?',
  'contact.faq.a7': 'চিকিৎসা জরুরি অবস্থার জন্য, অনুগ্রহ করে ৯১১ নম্বরে কল করুন অথবা আপনার নিকটস্থ জরুরি কক্ষে যান। আমাদের টেলিমেডিসিন পরিষেবাগুলি অ-জরুরি পরামর্শ এবং রুটিন মেডিকেল যত্নের জন্য।',
  'contact.faq.q8': 'আমি কি আপনার প্ল্যাটফর্মের মাধ্যমে ল্যাব পরীক্ষার ফলাফল পেতে পারি?',
  'contact.faq.a8': 'হ্যাঁ, ডাঃ স্মিথ আপনার পরামর্শের সময় ল্যাব ফলাফল পর্যালোচনা এবং আলোচনা করতে পারেন। আপনি আপনার সুরক্ষিত রোগী পোর্টালের মাধ্যমে আপনার পরীক্ষার ফলাফল আপলোড করতে পারেন অথবা আপনার অ্যাপয়েন্টমেন্টের আগে ইমেল করতে পারেন।',
  'contact.toast.missingInfoTitle': 'তথ্য অনুপস্থিত',
  'contact.toast.missingInfoDescription': 'অনুগ্রহ করে সমস্ত প্রয়োজনীয় ক্ষেত্র পূরণ করুন।',
  'contact.toast.messageSentTitle': 'বার্তা পাঠানো হয়েছে!',
  'contact.toast.messageSentDescription': 'আমাদের সাথে যোগাযোগ করার জন্য আপনাকে ধন্যবাদ। আমরা ২৪ ঘন্টার মধ্যে আপনার সাথে যোগাযোগ করব।',

  // Book Appointment Page
  'bookAppointment.toast.missingInfoTitle': 'তথ্য অনুপস্থিত',
  'bookAppointment.toast.missingInfoDescription': 'অনুগ্রহ করে সমস্ত প্রয়োজনীয় ক্ষেত্র পূরণ করুন।',
  'bookAppointment.toast.bookedTitle': 'অ্যাপয়েন্টমেন্ট বুক করা হয়েছে!',
  'bookAppointment.toast.bookedDescription': 'আপনার অ্যাপয়েন্টমেন্ট সফলভাবে নির্ধারিত হয়েছে। আপনি শীঘ্রই একটি নিশ্চিতকরণ ইমেল পাবেন।',
  'bookAppointment.title': 'আপনার অ্যাপয়েন্টমেন্ট বুক করুন',
  'bookAppointment.subtitle': 'আপনার সুবিধামত ডাঃ সারা স্মিথের সাথে পরামর্শের সময় নির্ধারণ করুন',
  'bookAppointment.cardTitle': 'অ্যাপয়েন্টমেন্টের বিবরণ',
  'bookAppointment.personalInfoTitle': 'ব্যক্তিগত তথ্য',
  'bookAppointment.fullNameLabel': 'পুরো নাম',
  'bookAppointment.fullNamePlaceholder': 'আপনার পুরো নাম লিখুন',
  'bookAppointment.emailLabel': 'ইমেল ঠিকানা',
  'bookAppointment.emailPlaceholder': 'আপনার ইমেল ঠিকানা লিখুন',
  'bookAppointment.phoneLabel': 'ফোন নম্বর',
  'bookAppointment.phonePlaceholder': 'আপনার ফোন নম্বর লিখুন',
  'bookAppointment.serviceTypeLabel': 'সেবার ধরন',
  'bookAppointment.selectServicePlaceholder': 'একটি সেবা নির্বাচন করুন',
  'bookAppointment.service.generalConsultation': 'সাধারণ পরামর্শ',
  'bookAppointment.service.followUpAppointment': 'ফলো-আপ অ্যাপয়েন্টমেন্ট',
  'bookAppointment.service.prescriptionRenewal': 'প্রেসক্রিপশন নবায়ন',
  'bookAppointment.service.symptomAssessment': 'উপসর্গ মূল্যায়ন',
  'bookAppointment.service.secondOpinion': 'দ্বিতীয় মতামত',
  'bookAppointment.service.chronicDiseaseManagement': 'দীর্ঘস্থায়ী রোগ ব্যবস্থাপনা',
  'bookAppointment.dateTimeTitle': 'তারিখ ও সময়',
  'bookAppointment.selectDateLabel': 'তারিখ নির্বাচন করুন',
  'bookAppointment.pickDatePlaceholder': 'একটি তারিখ নির্বাচন করুন',
  'bookAppointment.availableTimeSlotsLabel': 'উপলব্ধ সময় স্লট',
  'bookAppointment.timeSlot.nineAM': 'সকাল ৯:০০',
  'bookAppointment.timeSlot.nineThirtyAM': 'সকাল ৯:৩০',
  'bookAppointment.timeSlot.tenAM': 'সকাল ১০:০০',

  // Login Page
  'login.subtitle': 'আপনার অ্যাকাউন্টে সাইন ইন করুন',
  'login.welcomeBack': 'আপনাকে স্বাগতম',
  'login.patientTab': 'রোগী',
  'login.doctorTab': 'ডাক্তার',
  'login.patient.emailLabel': 'ইমেল ঠিকানা',
  'login.patient.emailPlaceholder': 'আপনার ইমেল লিখুন',
  'login.patient.passwordLabel': 'পাসওয়ার্ড',
  'login.patient.passwordPlaceholder': 'আপনার পাসওয়ার্ড লিখুন',
  'login.patient.forgotPassword': 'পাসওয়ার্ড ভুলে গেছেন?',
  'login.patient.signInButton': 'রোগী হিসাবে সাইন ইন করুন',
  'login.patient.noAccountText': 'অ্যাকাউন্ট নেই?',
  'login.patient.signUpLink': 'এখানে সাইন আপ করুন',
  'login.doctor.emailLabel': 'ডাক্তারের ইমেল',
  'login.doctor.emailPlaceholder': 'ডাক্তারের ইমেল লিখুন',
  'login.doctor.passwordLabel': 'পাসওয়ার্ড',
  'login.doctor.passwordPlaceholder': 'পাসওয়ার্ড লিখুন',
  'login.doctor.securePortalNotice': 'এটি শুধুমাত্র চিকিৎসা পেশাদারদের জন্য একটি সুরক্ষিত অ্যাডমিন পোর্টাল।',
  'login.doctor.signInButton': 'ডাক্তার হিসাবে সাইন ইন করুন',
  'login.securityNotice': 'আপনার তথ্য এন্টারপ্রাইজ-গ্রেড এনক্রিপশন দ্বারা সুরক্ষিত এবং HIPAA গোপনীয়তা মান মেনে চলে।',
  'login.toast.missingInfoTitle': 'তথ্য অনুপস্থিত',
  'login.toast.missingInfoDescription': 'অনুগ্রহ করে সমস্ত ক্ষেত্র পূরণ করুন।',
  'login.toast.patientLoginSuccessTitle': 'লগইন সফল!',
   'login.toast.patientLoginSuccessDescription': 'স্বাগতম! আপনার ড্যাশবোর্ডে পুনঃনির্দেশ করা হচ্ছে।',
   'login.toast.doctorLoginSuccessTitle': 'ডাক্তার লগইন সফল!',
   'login.toast.doctorLoginSuccessDescription': 'স্বাগতম, ডঃ স্মিথ!',

   // Register Page
   'register.subtitle': 'মেডিকমেট কেয়ারে আজই যোগ দিন',
   'register.welcome': 'রোগী বা ডাক্তার হিসাবে নিবন্ধন করুন',
   'register.patientTab': 'রোগী',
   'register.doctorTab': 'ডাক্তার',

   'register.patient.fullNameLabel': 'পুরো নাম *',
   'register.patient.fullNamePlaceholder': 'আপনার পুরো নাম লিখুন',
   'register.patient.emailLabel': 'ইমেইল *',
   'register.patient.emailPlaceholder': 'আপনার ইমেইল লিখুন',
   'register.patient.phoneLabel': 'ফোন নম্বর *',
   'register.patient.phonePlaceholder': 'আপনার ফোন নম্বর লিখুন',
   'register.patient.dobLabel': 'জন্ম তারিখ *',
   'register.patient.dobPlaceholder': 'আপনার জন্ম তারিখ নির্বাচন করুন',
   'register.patient.passwordLabel': 'পাসওয়ার্ড *',
   'register.patient.passwordPlaceholder': 'একটি শক্তিশালী পাসওয়ার্ড তৈরি করুন',
   'register.patient.confirmPasswordLabel': 'পাসওয়ার্ড নিশ্চিত করুন *',
   'register.patient.confirmPasswordPlaceholder': 'আপনার পাসওয়ার্ড নিশ্চিত করুন',
   'register.patient.agreeToTerms': 'আমি সম্মত',
   'register.patient.termsOfService': 'পরিষেবার শর্তাবলী',
   'register.patient.and': 'এবং',
   'register.patient.privacyPolicy': 'গোপনীয়তা নীতি',
   'register.patient.createAccountButton': 'অ্যাকাউন্ট তৈরি করুন',
   'register.patient.alreadyAccount': 'ইতিমধ্যে একটি অ্যাকাউন্ট আছে?',
   'register.patient.signInHere': 'এখানে সাইন ইন করুন',

   'register.doctor.securePortalNotice': 'ডাক্তার নিবন্ধনের জন্য মেডিকেল ক্রেডেনশিয়াল যাচাইকরণ প্রয়োজন।',
   'register.doctor.fullNameLabel': 'পুরো নাম *',
   'register.doctor.fullNamePlaceholder': 'আপনার পুরো নাম লিখুন',
   'register.doctor.emailLabel': 'পেশাদার ইমেইল *',
   'register.doctor.emailPlaceholder': 'আপনার পেশাদার ইমেইল লিখুন',
   'register.doctor.passwordLabel': 'পাসওয়ার্ড *',
   'register.doctor.passwordPlaceholder': 'একটি শক্তিশালী পাসওয়ার্ড তৈরি করুন',
   'register.doctor.confirmPasswordLabel': 'পাসওয়ার্ড নিশ্চিত করুন *',
   'register.doctor.confirmPasswordPlaceholder': 'আপনার পাসওয়ার্ড নিশ্চিত করুন',
   'register.doctor.agreeToTerms': 'আমি সম্মত',
   'register.doctor.termsOfService': 'পরিষেবার শর্তাবলী',
   'register.doctor.and': 'এবং',
   'register.doctor.privacyPolicy': 'গোপনীয়তা নীতি',
   'register.doctor.submitApplicationButton': 'ডাক্তার আবেদন জমা দিন',
   'register.doctor.alreadyAccount': 'ইতিমধ্যে একটি অ্যাকাউন্ট আছে?',
   'register.doctor.signInHere': 'এখানে সাইন ইন করুন',

  'login.doctor.password.placeholder': 'পাসওয়ার্ড লিখুন',
  'login.doctor.securePortalNoticeBn': 'এটি শুধুমাত্র চিকিৎসা পেশাদারদের জন্য একটি সুরক্ষিত অ্যাডমিন পোর্টাল।',
  'login.doctor.signInBn': 'ডাক্তার হিসাবে সাইন ইন করুন',
  'login.securityNotice.bn': 'আপনার তথ্য এন্টারপ্রাইজ-গ্রেড এনক্রিপশন দ্বারা সুরক্ষিত এবং HIPAA গোপনীয়তা মান মেনে চলে।',
  'login.toast.missingInfo': 'তথ্য অনুপস্থিত', // Changed key to avoid duplicate property names
  'login.toast.missingInfoDesc': 'অনুগ্রহ করে সমস্ত ক্ষেত্র পূরণ করুন।',
  'login.toast.patientLoginSuccess': 'লগইন সফল!',
  'login.toast.patientLoginSuccessDescription.bn': 'আপনাকে স্বাগতম! আপনার ড্যাশবোর্ডে পুনঃনির্দেশিত করা হচ্ছে।',
  'login.toast.doctorLoginSuccess': 'ডাক্তার লগইন সফল!', // Renamed to avoid duplicate property name
  'login.toast.doctorLoginSuccessDescription.bn': 'আপনাকে স্বাগতম, ডাঃ স্মিথ!',
  'bookAppointment.timeSlot.tenThirtyAM': 'সকাল ১০:৩০',
  'bookAppointment.timeSlot.elevenAM': 'সকাল ১১:০০',
  'bookAppointment.timeSlot.elevenThirtyAM': 'সকাল ১১:৩০',
  'bookAppointment.timeSlot.twoPM': 'দুপুর ২:০০',
  'bookAppointment.timeSlot.twoThirtyPM': 'দুপুর ২:৩০',
  'bookAppointment.timeSlot.threePM': 'দুপুর ৩:০০',
  'bookAppointment.timeSlot.threeThirtyPM': 'দুপুর ৩:৩০',
  'bookAppointment.timeSlot.fourPM': 'বিকাল ৪:০০',
  'bookAppointment.timeSlot.fourThirtyPM': 'বিকাল ৪:৩০',
  'bookAppointment.timeSlot.fivePM': 'বিকাল ৫:০০',
  'bookAppointment.notesPlaceholder': 'কোনো অতিরিক্ত নোট বা অনুরোধ?',
  'bookAppointment.confirmButton': 'অ্যাপয়েন্টমেন্ট নিশ্চিত করুন',

  // Medicine Page - Medicine Details
  'medicine.ibuprofen.usage': 'ব্যথা উপশম ও প্রদাহরোধী',
  'medicine.ibuprofen.description': 'মাথাব্যথা, পেশী ব্যথা এবং প্রদাহের জন্য কার্যকর উপশম।',
  'medicine.amoxicillin.usage': 'অ্যান্টিবায়োটিক',
  'medicine.amoxicillin.description': 'ব্যাকটেরিয়া সংক্রমণের জন্য ব্রড-স্পেকট্রাম অ্যান্টিবায়োটিক।',
  'medicine.lisinopril.usage': 'রক্তচাপ নিয়ন্ত্রণ',
  'medicine.lisinopril.description': 'উচ্চ রক্তচাপ নিয়ন্ত্রণের জন্য এসিই ইনহিবিটর।',
  'medicine.metformin.usage': 'ডায়াবেটিস ব্যবস্থাপনা',
  'medicine.metformin.description': 'টাইপ 2 ডায়াবেটিসের জন্য প্রথম সারির চিকিৎসা।',
  'medicine.albuterol.usage': 'অ্যাজমা ইনহেলার',
  'medicine.albuterol.description': 'অ্যাজমা উপশমের জন্য দ্রুত কার্যকর ব্রঙ্কোডাইলেটর।',
  'medicine.omeprazole.usage': 'অ্যাসিড রিফ্লাক্স উপশম',
  'medicine.omeprazole.description': 'গ্যাস্ট্রিক অ্যাসিড কমানোর জন্য প্রোটন পাম্প ইনহিবিটর।',

  'medicine.ibuprofen.price': '৳১২.৯৯',
  'medicine.amoxicillin.price': '৳১৮.৫০',
  'medicine.lisinopril.price': '৳১৫.২৫',
  'medicine.metformin.price': '৳২২.০০',
  'medicine.albuterol.price': '৳৩৫.৭৫',
  'medicine.omeprazole.price': '৳১৪.৫০',

  // Emergency Contact
  'contact.emergency.title': 'জরুরী যোগাযোগ',
  'contact.emergency.subtitle': 'মেডিকেল জরুরি অবস্থার জন্য',
  'contact.emergency.description': 'অনুগ্রহ করে ৯১১ নম্বরে কল করুন অথবা আপনার নিকটস্থ জরুরি কক্ষে যান। আমাদের টেলিমেডিসিন পরিষেবাগুলি অ-জরুরি পরামর্শের জন্য.',

  // About Page
  'about.hero.badge': 'মেডিকমেট সম্পর্কে',
  'about.hero.title': 'স্বাস্থ্যসেবায় বিপ্লব আনছি',
  'about.hero.subtitle': 'একবারে একজন রোগীর জন্য',
  'about.hero.description': 'মেডিকমেট একটি সাধারণ বিশ্বাস থেকে জন্ম নিয়েছে: প্রত্যেকের মানসম্পন্ন, ব্যক্তিগতকৃত স্বাস্থ্যসেবা পাওয়ার অধিকার আছে। উদ্ভাবনী প্রযুক্তি এবং সহানুভূতিশীল যত্নের মাধ্যমে, আমরা সেই স্বপ্নকে বাস্তবে পরিণত করছি।',
  'about.story.title': 'আমাদের গল্প',
  'about.story.paragraph1': 'ডাঃ সারা স্মিথ ২০১৯ সালে মেডিকমেট প্রতিষ্ঠা করেন একটি স্পষ্ট লক্ষ্য নিয়ে: প্রযুক্তি ব্যবহার করে রোগী এবং মানসম্পন্ন স্বাস্থ্যসেবার মধ্যে ব্যবধান দূর করা। সময়মতো চিকিৎসা সেবা পেতে রোগীদের যে চ্যালেঞ্জগুলোর মুখোমুখি হতে হয়, তা প্রত্যক্ষ করে তিনি এমন একটি প্ল্যাটফর্মের স্বপ্ন দেখেছিলেন যা স্বাস্থ্যসেবাকে আরও সহজলভ্য, সাশ্রয়ী এবং ব্যক্তিগত করে তুলবে।',
  'about.story.paragraph2': 'একটি ছোট টেলিমেডিসিন অনুশীলন হিসাবে যা শুরু হয়েছিল, তা এখন একাধিক রাজ্যে ১,২০০ এরও বেশি রোগীকে সেবা প্রদানকারী একটি ব্যাপক স্বাস্থ্যসেবা প্ল্যাটফর্মে পরিণত হয়েছে। শ্রেষ্ঠত্বের প্রতি আমাদের প্রতিশ্রুতি এবং রোগী-প্রথম দৃষ্টিভঙ্গি আমাদের ৯৮% সন্তুষ্টির হার এবং ডিজিটাল স্বাস্থ্য খাতে অসংখ্য প্রশংসা অর্জন করেছে।',
  'about.story.button': 'ডাঃ স্মিথ সম্পর্কে আরও জানুন',
  'about.timeline.title': 'আমাদের যাত্রা',
  'about.timeline.description': 'স্বাস্থ্যসেবা পরিবর্তনে আমাদের মিশনের মূল মাইলফলক',
  'about.timeline.year1': '২০১৯',
  'about.timeline.title1': 'মেডিকমেট প্রতিষ্ঠিত',
  'about.timeline.description1': 'ডাঃ সারা স্মিথ মানসম্পন্ন স্বাস্থ্যসেবাকে প্রযুক্তির মাধ্যমে সবার জন্য সহজলভ্য করার স্বপ্ন নিয়ে মেডিকমেট প্রতিষ্ঠা করেন।',
  'about.timeline.year2': '২০২০',
  'about.timeline.title2': 'টেলিমেডিসিন অগ্রদূত',
  'about.timeline.description2': 'মহামারীর সময় ব্যাপক টেলিমেডিসিন সেবা প্রদানকারী প্রথম অনুশীলনগুলির মধ্যে একটি হয়ে ওঠে।',
  'about.timeline.year3': '২০২২',
  'about.timeline.title3': '১০০০+ রোগীকে সেবা প্রদান',
  'about.timeline.description3': '৯৮% সন্তুষ্টির হার নিয়ে ১০০০ এরও বেশি রোগীকে সেবা প্রদানের মাইলফলক অর্জন করেছে।',
  'about.timeline.year4': '২০২৪',
  'about.timeline.title4': 'উন্নত প্ল্যাটফর্ম চালু',
  'about.timeline.description4': 'এআই-সহায়তা ডায়াগনস্টিকস এবং উন্নত রোগীর অভিজ্ঞতা সহ আমাদের উন্নত অনলাইন প্ল্যাটফর্ম চালু করা হয়েছে।',
  'about.achievements.title': 'আমাদের প্রভাব',
  'about.achievements.description': 'আমাদের শ্রেষ্ঠত্বের প্রতিশ্রুতির প্রতিফলনকারী সংখ্যা',
  'about.achievements.patientsNumber': '১,২০০+',
  'about.achievements.patientsLabel': 'সন্তুষ্ট রোগী',
  'about.achievements.satisfactionRateNumber': '৯৮%',
  'about.achievements.satisfactionRateLabel': 'সন্তুষ্টির হার',
  'about.achievements.responseTimeNumber': '< ২ ঘন্টা',
  'about.achievements.responseTimeLabel': 'গড় প্রতিক্রিয়ার সময়',
  'about.achievements.experienceNumber': '১৫+',
  'about.achievements.experienceLabel': 'বছরের অভিজ্ঞতা',

  // Medicine Page - Conditions
  'medicine.condition.allConditions': 'সমস্ত অবস্থা',
  'medicine.condition.painManagement': 'ব্যথা ব্যবস্থাপনা',
  'medicine.condition.infections': 'সংক্রমণ',
  'medicine.condition.cardiovascular': 'কার্ডিওভাসকুলার',
  'medicine.condition.diabetes': 'ডায়াবেটিস',
  'medicine.condition.respiratory': 'শ্বাসযন্ত্র',
  'medicine.condition.digestive': 'পাচনতন্ত্র',

  // Medicine Page - Availability
  'medicine.availability.all': 'সব',
  'medicine.availability.inStock': 'স্টকে আছে',
  'medicine.availability.prescriptionRequired': 'প্রেসক্রিপশন প্রয়োজন',

  // Medicine Page - Diagnostic Tests
  'medicine.diagnostic.bloodTest.name': 'কমপ্লিট ব্লাড কাউন্ট (সিবিসি)',
  'medicine.diagnostic.bloodTest.category': 'রক্ত পরীক্ষা',
  'medicine.diagnostic.bloodTest.description': 'রক্তের বিভিন্ন উপাদান পরিমাপ করে, যা সংক্রমণ, রক্তাল্পতা এবং অন্যান্য রোগ নির্ণয়ে সহায়ক।',
  'medicine.diagnostic.urineTest.name': 'ইউরিনালিসিস',
  'medicine.diagnostic.urineTest.category': 'মূত্র পরীক্ষা',
  'medicine.diagnostic.urineTest.description': 'মূত্রের উপাদান পরীক্ষা করে বিভিন্ন রোগ ও অবস্থা পরীক্ষা করে।',
  'medicine.diagnostic.xray.name': 'চেস্ট এক্স-রে',
  'medicine.diagnostic.xray.category': 'ইমেজিং',
  'medicine.diagnostic.xray.description': 'হৃদপিণ্ড, ফুসফুস, রক্তনালী এবং বুকের ও মেরুদণ্ডের হাড়ের ছবি সরবরাহ করে।',
  'medicine.diagnostic.mri.name': 'এমআরআই স্ক্যান (মস্তিষ্ক)',
  'medicine.diagnostic.mri.category': 'ইমেজিং',
  'medicine.diagnostic.mri.description': 'মস্তিষ্ক এবং আশেপাশের টিস্যুগুলির বিস্তারিত ছবি, যা বিভিন্ন স্নায়বিক অবস্থা নির্ণয়ে ব্যবহৃত হয়।',
  'medicine.diagnostic.ecg.name': 'ইলেক্ট্রোকার্ডিওগ্রাম (ইসিজি)',
  'medicine.diagnostic.ecg.category': 'কার্ডিয়াক পরীক্ষা',
  'medicine.diagnostic.ecg.description': 'হৃদপিণ্ডের বৈদ্যুতিক সংকেত রেকর্ড করে হৃদরোগ নির্ণয় করে।',
  'medicine.diagnostic.ultrasound.name': 'পেটের আল্ট্রাসাউন্ড',
  'medicine.diagnostic.ultrasound.category': 'ইমেজিং',
  'medicine.diagnostic.ultrasound.description': 'পেটের ভেতরের অঙ্গ-প্রত্যঙ্গ এবং কাঠামোর ছবি তৈরি করতে শব্দ তরঙ্গ ব্যবহার করে।',
  'medicine.diagnostic.bloodTest.price': '৳৪৯.৯৯',
  'medicine.diagnostic.xray.price': '৳১২০.০০',
  'medicine.diagnostic.ecg.price': '৳৭৫.০০',
  'medicine.diagnostic.ultrasound.price': '৳৭৫.০০',
  'medicine.diagnostic.bookTest': 'টেস্ট বুক করুন',
  'medicine.diagnostic.popular': 'জনপ্রিয়',
  'medicine.diagnostic.common': 'সাধারণ',
  'medicine.diagnostic.specialized': 'বিশেষায়িত',
  'medicine.diagnostic.fastingRequired': 'খালি পেটে প্রয়োজন',
  'medicine.diagnostic.doctorReferral': 'ডাক্তারের রেফারেল',
  'medicine.diagnostic.preparationRequired': 'প্রস্তুতি প্রয়োজন',
  'medicine.diagnostic.time.12hours': '১২ ঘন্টা',
  'medicine.diagnostic.time.1-2days': '১-২ দিন',
  'medicine.diagnostic.time.2-3days': '২-৩ দিন',
  'medicine.diagnostic.time.1-2weeks': '১-২ সপ্তাহ',
  'medicine.diagnostic.xray.name.chest': 'বুকের এক্স-রে',
  'medicine.diagnostic.xray.categoryName': 'ইমেজিং পরীক্ষা',
  'medicine.diagnostic.xray.details': 'বুক, হৃৎপিণ্ড, ফুসফুস, রক্তনালী এবং হাড়ের ছবি তৈরি করে রোগ নির্ণয় করতে সাহায্য করে।',
  'medicine.diagnostic.xray.cost': '৳১২০.০০',
  'medicine.diagnostic.lipidPanel.name': 'লিপিড প্যানেল',
  'medicine.diagnostic.lipidPanel.category': 'কার্ডিওভাসকুলার স্বাস্থ্য',
  'medicine.diagnostic.lipidPanel.description': 'কার্ডিওভাসকুলার রোগের ঝুঁকি নির্ণয় করতে কোলেস্টেরলের মাত্রা পরিমাপ করে। এতে মোট কোলেস্টেরল, এইচডিএল, এলডিএল এবং ট্রাইগ্লিসারাইড অন্তর্ভুক্ত।',
  'medicine.diagnostic.lipidPanel.price': '৳৬৫.০০',
  'medicine.diagnostic.brainMri.name': 'ব্রেন এমআরআই',
  'medicine.diagnostic.brainMri.category': 'উন্নত ইমেজিং',
  'medicine.diagnostic.brainMri.description': 'চৌম্বক ক্ষেত্র এবং রেডিও তরঙ্গ ব্যবহার করে মস্তিষ্ক এবং ব্রেন স্টেমের বিস্তারিত ছবি তৈরি করে। টিউমার, স্ট্রোক এবং অন্যান্য অবস্থা নির্ণয় করতে সাহায্য করে।',
  'medicine.diagnostic.brainMri.price': '৳৮৫০.০০',
  'medicine.diagnostic.colonoscopy.name': 'কোলনস্কোপি',
  'medicine.diagnostic.colonoscopy.category': 'গ্যাস্ট্রোইনটেস্টাইনাল পদ্ধতি',
  'medicine.diagnostic.colonoscopy.description': 'পলিপ, আলসার এবং ক্যান্সারের মতো অস্বাভাবিকতা সনাক্ত করতে কোলনের আস্তরণ পরীক্ষা করে। এতে সেডেশন এবং পুনরুদ্ধারের সময় অন্তর্ভুক্ত।',
  'medicine.diagnostic.colonoscopy.price': '৳১,২০০.০০',
  'medicine.diagnostic.helpChoosingTest.title': 'সঠিক পরীক্ষা বেছে নিতে সাহায্য প্রয়োজন?',
  'medicine.category.allCategories': 'সকল ক্যাটাগরি',
  'medicine.category.bloodTests': 'রক্ত পরীক্ষা',
  'medicine.category.imaging': 'ইমেজিং',
  'medicine.category.cardiovascular': 'কার্ডিওভাসকুলার',
  'medicine.category.neurological': 'নিউরোলজিক্যাল',
  'medicine.category.gastrointestinal': 'গ্যাস্ট্রোইনটেস্টাইনাল',
  'medicine.diagnostic.helpChoosingTest.description': 'আমাদের স্বাস্থ্যসেবা পেশাদাররা আপনার লক্ষণ এবং স্বাস্থ্য উদ্বেগের জন্য কোন ডায়াগনস্টিক পরীক্ষাগুলি উপযুক্ত তা নির্ধারণ করতে আপনাকে সাহায্য করতে পারে।',
  'medicine.diagnostic.askDoctor': 'ডাক্তারকে জিজ্ঞাসা করুন',
  'medicine.diagnostic.consultDoctor': 'ডাক্তারের সাথে পরামর্শ করুন',

  // Cart
  'cart.title': 'আপনার কার্ট',
  'cart.empty.title': 'আপনার কার্ট খালি',
  'cart.empty.description': 'শুরু করতে কিছু ঔষধ বা ডায়াগনস্টিক পরীক্ষা যোগ করুন।',
  'cart.continueShopping': 'কেনাকাটা চালিয়ে যান',
  'cart.clearAll': 'সব মুছে ফেলুন',
  'cart.orderSummary': 'অর্ডার সারসংক্ষেপ',
  'cart.subtotal': 'উপমোট',
  'cart.shipping': 'পরিবহন',
  'cart.free': 'বিনামূল্যে',
  'cart.total': 'মোট',
  'cart.checkout': 'চেকআউটে যান',
  'cart.medicine': 'ঔষধ',
  'cart.diagnostic': 'ডায়াগনস্টিক পরীক্ষা',
  'cart.itemAdded': 'আইটেম যোগ হয়েছে',
  'cart.addedToCart': 'আপনার কার্টে যোগ করা হয়েছে',

  'medicine.teleconsult.title': 'প্রেসক্রিপশন প্রয়োজন?',
  'medicine.teleconsult.description': 'ব্যক্তিগতকৃত ঔষধের সুপারিশ এবং ডিজিটাল প্রেসক্রিপশন পেতে ডাঃ সারাহ স্মিথের সাথে পরামর্শ করুন।',
  'medicine.teleconsult.button': 'পরামর্শের সময় নির্ধারণ করুন',

  // Blog Page
  'blog.hero.title': 'মেডিকমেট স্বাস্থ্য ব্লগ',
  'blog.hero.description': 'বিশেষজ্ঞের অন্তর্দৃষ্টি, স্বাস্থ্য টিপস এবং চিকিৎসা সংক্রান্ত তথ্য যা আপনাকে স্বাস্থ্যকর জীবনযাপন করতে সাহায্য করবে',
  'blog.hero.subscribeButton': 'আপডেটের জন্য সাবস্ক্রাইব করুন',
  'blog.hero.browseCategoriesButton': 'ক্যাটাগরি ব্রাউজ করুন',
  'blog.featuredArticles.title': 'বৈশিষ্ট্যযুক্ত নিবন্ধ',
  'blog.featuredArticles.viewAllButton': 'সকল নিবন্ধ দেখুন',
  'blog.latestHealthInsights.title': 'সর্বশেষ স্বাস্থ্য অন্তর্দৃষ্টি',
  'blog.healthTips.title': 'স্বাস্থ্য টিপস ও পরামর্শ',
  'blog.healthTips.description': 'সুস্বাস্থ্য বজায় রাখার জন্য সঠিক পুষ্টি, নিয়মিত ব্যায়াম, পর্যাপ্ত ঘুম এবং মানসিক চাপ নিয়ন্ত্রণ সহ একটি সামগ্রিক পদ্ধতির প্রয়োজন। মেডিকমেটে আমরা আমাদের রোগীদেরকে সঠিক স্বাস্থ্য সিদ্ধান্ত নিতে জ্ঞান দিয়ে ক্ষমতায়ন করতে বিশ্বাস করি।',
  'blog.healthTips.quickTipsTitle': 'দ্রুত স্বাস্থ্য টিপস:',
  'blog.healthTips.tip1': 'প্রতিদিন কমপক্ষে ৮ গ্লাস জল পান করে শরীরকে সতেজ রাখুন',
  'blog.healthTips.tip2': 'প্রতি রাতে ৭-৯ ঘন্টা মানসম্মত ঘুমের লক্ষ্য রাখুন',
  'blog.healthTips.tip3': 'আপনার খাদ্যে বিভিন্ন রঙিন ফল ও সবজি অন্তর্ভুক্ত করুন',
  'blog.healthTips.tip4': 'চোখের চাপ এবং মানসিক ক্লান্তি কমাতে কাজের সময় ছোট বিরতি নিন',
  'blog.healthTips.tip5': 'স্ট্রেস মোকাবেলায় মাইন্ডফুলনেস বা মেডিটেশন অনুশীলন করুন',
  'blog.healthTips.conclusion': 'মনে রাখবেন, ছোট, ধারাবাহিক পরিবর্তনগুলি প্রায়শই সবচেয়ে টেকসই স্বাস্থ্য উন্নতির দিকে নিয়ে যায়। আপনার নির্দিষ্ট প্রয়োজন অনুযায়ী ব্যক্তিগত পরামর্শের জন্য আমাদের স্বাস্থ্যসেবা পেশাদারদের সাথে পরামর্শ করুন।',
  'blog.cta.title': 'স্বাস্থ্য বিষয়ক প্রশ্ন আছে?',
  'blog.cta.description': 'আমাদের যোগ্য স্বাস্থ্যসেবা পেশাদারদের দল আপনাকে ব্যক্তিগত পরামর্শ দিয়ে সাহায্য করতে প্রস্তুত।',
    'blog.cta.bookConsultationButton': 'একটি পরামর্শ বুক করুন',
    'blog.cta.contactUsButton': 'আমাদের সাথে যোগাযোগ করুন',

    'blog.featuredPosts.post1.title': 'টেলিমেডিসিন বোঝা: স্বাস্থ্যসেবার ভবিষ্যৎ',
    'blog.featuredPosts.post1.excerpt': 'টেলিমেডিসিন কীভাবে রোগীর যত্নে বিপ্লব ঘটাচ্ছে এবং স্বাস্থ্যসেবাকে আগের চেয়ে আরও সহজলভ্য করে তুলছে তা অন্বেষণ করুন।',
    'blog.featuredPosts.post1.category': 'টেলিমেডিসিন',
    'blog.featuredPosts.post1.author': 'ডাঃ সারাহ জনসন',
    'blog.featuredPosts.post1.date': 'জুন ১৫, ২০২৪',
    'blog.featuredPosts.post1.readTime': '৮ মিনিট পড়া',
    'blog.featuredPosts.post1.tag1': 'টেলিমেডিসিন',
    'blog.featuredPosts.post1.tag2': 'ডিজিটাল স্বাস্থ্য',
    'blog.featuredPosts.post1.tag3': 'স্বাস্থ্যসেবা অ্যাক্সেস',

    'blog.featuredPosts.post2.title': 'প্রতিরোধমূলক স্বাস্থ্য ব্যবস্থা যা সবার জানা উচিত',
    'blog.featuredPosts.post2.excerpt': 'প্রয়োজনীয় প্রতিরোধমূলক স্বাস্থ্য ব্যবস্থা সম্পর্কে জানুন যা আপনাকে সর্বোত্তম স্বাস্থ্য বজায় রাখতে এবং সাধারণ রোগ প্রতিরোধ করতে সাহায্য করতে পারে।',
    'blog.featuredPosts.post2.category': 'প্রতিরোধমূলক যত্ন',
    'blog.featuredPosts.post2.author': 'ডাঃ মাইকেল চেন',
    'blog.featuredPosts.post2.date': 'জুন ১০, ২০২৪',
    'blog.featuredPosts.post2.readTime': '৬ মিনিট পড়া',
    'blog.featuredPosts.post2.tag1': 'প্রতিরোধমূলক যত্ন',
    'blog.featuredPosts.post2.tag2': 'স্বাস্থ্য টিপস',
    'blog.featuredPosts.post2.tag3': 'সুস্থতা',

    'blog.featuredPosts.post3.title': 'ডিজিটাল যুগে মানসিক স্বাস্থ্য',
    'blog.featuredPosts.post3.excerpt': 'আমাদের ক্রমবর্ধমান ডিজিটাল বিশ্বের চ্যালেঞ্জগুলি নেভিগেট করার সময় কীভাবে ভাল মানসিক স্বাস্থ্য বজায় রাখা যায় তার কৌশলগুলি আবিষ্কার করুন।',
    'blog.featuredPosts.post3.category': 'মানসিক স্বাস্থ্য',
    'blog.featuredPosts.post3.author': 'ডাঃ এমিলি রড্রিগেজ',
    'blog.featuredPosts.post3.date': 'জুন ৫, ২০২৪',
    'blog.featuredPosts.post3.readTime': '৭ মিনিট পড়া',
    'blog.featuredPosts.post3.tag1': 'মানসিক স্বাস্থ্য',
    'blog.featuredPosts.post3.tag2': 'ডিজিটাল সুস্থতা',
    'blog.featuredPosts.post3.tag3': 'স্ট্রেস ম্যানেজমেন্ট',

    'blog.recentArticles.title': 'সাম্প্রতিক নিবন্ধ',
    'blog.recentPosts.post1.title': 'রোগ প্রতিরোধ ক্ষমতা স্বাস্থ্যে পুষ্টির ভূমিকা',
    'blog.recentPosts.post1.category': 'পুষ্টি',
    'blog.recentPosts.post1.date': 'জুন ১, ২০২৪',
    'blog.recentPosts.post1.readTime': '৫ মিনিট পড়া',

    'blog.recentPosts.post2.title': 'সাধারণ ঔষধ এবং তাদের পার্শ্ব প্রতিক্রিয়া বোঝা',
    'blog.recentPosts.post2.category': 'ঔষধ',
    'blog.recentPosts.post2.date': 'মে ২৮, ২০২৪',
    'blog.recentPosts.post2.readTime': '৬ মিনিট পড়া',

    'blog.recentPosts.post3.title': 'ঘুমের স্বাস্থ্যবিধি: ভাল বিশ্রামের জন্য টিপস',
    'blog.recentPosts.post3.category': 'সুস্থতা',
    'blog.recentPosts.post3.date': 'মে ২৫, ২০২৪',
    'blog.recentPosts.post3.readTime': '৪ মিনিট পড়া',

    'blog.recentPosts.post4.title': 'দীর্ঘস্থায়ী রোগ ব্যবস্থাপনা: একটি বিস্তারিত নির্দেশিকা',
    'blog.recentPosts.post4.category': 'দীর্ঘস্থায়ী যত্ন',
    'blog.recentPosts.post4.date': 'মে ২০, ২০২৪',
    'blog.recentPosts.post4.readTime': '৯ মিনিট পড়া',

    'blog.categories.telemedicine': 'টেলিমেডিসিন',
    'blog.categories.preventiveCare': 'প্রতিরোধমূলক যত্ন',
    'blog.categories.mentalHealth': 'মানসিক স্বাস্থ্য',
    'blog.categories.nutrition': 'পুষ্টি',
    'blog.categories.medications': 'ঔষধ',
    'blog.categories.wellness': 'সুস্থতা',
    'blog.categories.chronicCare': 'দীর্ঘস্থায়ী যত্ন',

    'blog.sidebar.categoriesTitle': 'বিভাগ',
    'blog.sidebar.newsletterTitle': 'আমাদের নিউজলেটারে সাবস্ক্রাইব করুন',
    'blog.sidebar.newsletterDescription': 'সর্বশেষ স্বাস্থ্য টিপস এবং চিকিৎসা আপডেট সরাসরি আপনার ইনবক্সে পান।',
    'blog.sidebar.newsletterPlaceholder': 'আপনার ইমেইল ঠিকানা',
    'blog.sidebar.newsletterButton': 'সাবস্ক্রাইব করুন',
    'blog.sidebar.tagsTitle': 'জনপ্রিয় ট্যাগ',

  // About Page
  'about.vision.title': 'আমাদের লক্ষ্য',
  'about.vision.description': 'মেডিকমেট একটি বিশ্বাস থেকে জন্ম নিয়েছে: প্রত্যেকেরই মানসম্মত, ব্যক্তিগতকৃত স্বাস্থ্যসেবা পাওয়ার অধিকার আছে। উদ্ভাবনী প্রযুক্তি এবং সহানুভূতিশীল যত্নের মাধ্যমে, আমরা সেই স্বপ্নকে বাস্তবে পরিণত করছি।',
  'about.mission.title': 'আমাদের মিশন',
  'about.mission.description': 'ব্যক্তিগতকৃত, সহানুভূতিশীল এবং প্রমাণ-ভিত্তিক স্বাস্থ্যসেবা প্রদানের জন্য উদ্ভাবনী প্রযুক্তির মাধ্যমে। আমরা আমাদের রোগীদের সাথে দীর্ঘস্থায়ী সম্পর্ক গড়ে তুলতে প্রতিশ্রুতিবদ্ধ, যাতে তারা বাড়িতে বসেই সর্বোচ্চ মানের যত্ন পান।',

  'about.cta.title': 'উন্নত স্বাস্থ্যসেবার অভিজ্ঞতা নিতে প্রস্তুত?',
  'about.cta.description': 'হাজার হাজার সন্তুষ্ট রোগীর সাথে যোগ দিন যারা মেডিকমেটের ব্যক্তিগতকৃত স্বাস্থ্যসেবাগুলির সুবিধা এবং গুণমান আবিষ্কার করেছেন।',
  'about.cta.bookAppointmentButton': 'আপনার অ্যাপয়েন্টমেন্ট বুক করুন',
  'about.cta.contactUsButton': 'আমাদের সাথে যোগাযোগ করুন',

    // Diagnostic Test Categories
  'medicine.diagnostic.category.allCategories': 'সকল বিভাগ',
  'medicine.diagnostic.category.bloodTest': 'রক্ত পরীক্ষা',
  'medicine.diagnostic.category.urineTest': 'মূত্র পরীক্ষা',
  'medicine.diagnostic.category.imaging': 'ইমেজিং',
  'medicine.diagnostic.category.cardiacTest': 'কার্ডিয়াক পরীক্ষা',

  // Diagnostic Test Price and Time
  'medicine.diagnostic.price': 'মূল্য',
  'medicine.diagnostic.resultsTime': 'ফলাফল সময়',
  'medicine.diagnostic.time.24hours': '২৪ ঘন্টা',
  'medicine.diagnostic.time.48hours': '৪৮ ঘন্টা',
  'medicine.diagnostic.time.72hours': '৭২ ঘন্টা',
  'medicine.diagnostic.time.3days': '৩ দিন',
  'medicine.diagnostic.time.5days': '৫ দিন',
  'medicine.diagnostic.time.1week': '১ সপ্তাহ',
};

type LanguageProviderProps = {
  children: ReactNode;
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    const translations = language === 'en' ? enTranslations : bnTranslations;
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};